"use client";

import { useState } from "react";
import { Filter } from "lucide-react";
import type { AthleteListItem, GroupListItem } from "@/lib/data";

export function DashboardFilters({ athletes, groups, values }: { athletes: AthleteListItem[]; groups: GroupListItem[]; values: { scope: string; athlete?: string; group?: string; range: string; from?: string; to?: string } }) {
  const [scope, setScope] = useState(values.scope);
  const [range, setRange] = useState(values.range);
  const [from, setFrom] = useState(values.from ?? "");
  const [to, setTo] = useState(values.to ?? "");
  const controlClass = "min-h-11 w-full rounded-xl border border-[#d4dfe4] bg-white px-3 text-sm font-semibold text-[#304a5d] outline-none focus:border-[#16a5b8] sm:w-auto";
  const fieldClass = "w-full sm:w-auto";
  return <form method="get" className="surface-card grid grid-cols-1 items-end gap-3 p-4 sm:flex sm:flex-wrap"><div className="mr-1 hidden size-10 place-items-center rounded-xl bg-[#e7f3f4] text-[#0a6f7e] sm:grid"><Filter className="size-4" /></div><label className={fieldClass}><span className="mb-1.5 block text-[.65rem] font-bold uppercase tracking-[.1em] text-[#82929d]">View</span><select name="scope" value={scope} onChange={(event) => setScope(event.target.value)} className={controlClass}><option value="all">Whole team</option><option value="men">All men</option><option value="women">All women</option><option value="group">Training category</option><option value="individual">Individual athlete</option></select></label>{scope === "individual" && <label className={fieldClass}><span className="mb-1.5 block text-[.65rem] font-bold uppercase tracking-[.1em] text-[#82929d]">Athlete</span><select name="athlete" defaultValue={values.athlete} className={`${controlClass} sm:max-w-56`} required><option value="">Select athlete</option>{athletes.map((athlete) => <option key={athlete.id} value={athlete.id}>{athlete.displayName}</option>)}</select></label>}{scope === "group" && <label className={fieldClass}><span className="mb-1.5 block text-[.65rem] font-bold uppercase tracking-[.1em] text-[#82929d]">Category</span><select name="group" defaultValue={values.group} className={controlClass} required><option value="">Select category</option>{groups.map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</select></label>}<label className={fieldClass}><span className="mb-1.5 block text-[.65rem] font-bold uppercase tracking-[.1em] text-[#82929d]">Timeframe</span><select name="range" value={range} onChange={(event) => setRange(event.target.value)} className={controlClass}><option value="week">Last 7 days</option><option value="month">Last 30 days</option><option value="all">All time</option><option value="custom">Custom dates</option></select></label>{range === "custom" && <><label className={fieldClass}><span className="mb-1.5 block text-[.65rem] font-bold uppercase tracking-[.1em] text-[#82929d]">From</span><input type="date" name="from" value={from} max={to || undefined} onChange={(event) => setFrom(event.target.value)} className={controlClass} required /></label><label className={fieldClass}><span className="mb-1.5 block text-[.65rem] font-bold uppercase tracking-[.1em] text-[#82929d]">To</span><input type="date" name="to" value={to} min={from || undefined} onChange={(event) => setTo(event.target.value)} className={controlClass} required /></label></>}<button className="min-h-11 w-full rounded-xl bg-[#0a304a] px-5 text-sm font-semibold text-white sm:w-auto">Apply filters</button></form>;
}
